### ISSUE TITLE
kicksecure-minimal install fails because Kernel 'pvgrub2-pvh' is not installed.

### ISSUE THREAD

**Issue by kennethrrosen** [ben-grande/qusal#71]
### Commitment

I confirm that I have read the following resources:

- [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

R4.2.1

### Brief summary

qubesadmin for kicksecure-minimal install fails because `Kernel 'pvgrub2-pvh'` is not installed.

### Steps to reproduce

Run `sudo qubesctl state.apply kicksecure-minimal.prefs` 

### Expected behavior

Completes without errors, allows user to move onto installation steps. 

### Actual behavior

Running `sudo qubesctl state.apply kicksecure-minimal.prefs` results in:

```
          ID: kicksecure-17-minimal
    Function: qvm.vm
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.11/site-packages/salt/state.py", line 2423, in call
                  ret = self.states[cdata["full"]](
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1293, in wrapper
                  return f(*args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^
                File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 435, in vm
                  status = globals()[action](name, *_varargs, **keywords)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 293, in prefs
                  return _state_action('qvm.prefs', name, *varargs, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 137, in _state_action
                  status = __salt__[_action](*varargs, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/var/cache/salt/minion/extmods/modules/ext_module_qvm.py", line 956, in prefs
                  setattr(args.vm, dest, value_new)
                File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 376, in __setattr__
                  self.qubesd_call(
                File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 76, in qubesd_call
                  return self.app.qubesd_call(dest, method, arg, payload,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/qubesadmin/app.py", line 787, in qubesd_call
                  return self._parse_qubesd_response(return_data)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 111, in _parse_qubesd_response
                  raise exc_class(format_string, *args)
              qubesadmin.exc.QubesPropertyValueError: Kernel 'pvgrub2-pvh' not installed
     Started: 00:01:11.865921
    Duration: 182.187 ms

```

.

**Comment by kennethrrosen** [comment]
Working now. Thanks!
